apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
  namespace: weather
  labels:
    app: weatherapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: aycaoktay/weatherapp-nodejs:73
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  namespace: weather
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: weatherapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-app
  namespace: weather
spec:
  ingressClassName: nginx
  rules:
  - host: weatherapp.anka.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weatherapp-service
            port:
              number: 80